print('Linux 1: Введение в Linux')
print('4	Data and Databases 1: Основные понятия и базовый синтаксис выборки')
print('5	German lesson 1 basic	German')
print('6	Python 3: Операторы, выражения')
print('7	Python 4: Логический тип данных и сравнения')
print('8	Linux 2: Первые команды')
print('9	Data and Databases 2: Более сложные инструменты выборки и правильный CodeStyle')
print('10	Python 5: Условный оператор if')
print('11	Python 6: Python Summary session 1')
print('12	Data and Databases 3: Summary session 1	Data and Databases')
print('13	Linux 3: Практикум 1')